export enum Estilo{
    PILSEN = 'Pilsen',
    MUNICH_HELLES = 'Munich Helles',
    VIENNA_LAGER = 'Vienna Lager',
    OKTOBERFEST = 'Oktoberfest ',
    BOCK = 'Bock' ,
    ALTBIER = 'Altbier',
    ENGLISH_PALE_ALE = 'English Pale Ale',
    ENGLISH_BROWN_ALE = 'English Brown Ale',
    INDIA_PALE_ALE = 'India Pale Ale',
    AMERICAN_IPA = 'American IPA',
    IMPERIAL_IPA = 'Imperial IPA',
    NEW_ENGLAND_IPA = 'New England IPA',
    PORTER = 'Porter',
    STOUT = 'Stout' ,
    WEIZENBIER = 'Weizenbier',
    WITBIER = 'Witbier',
    BELGIAN_PALE_ALE = 'Belgian Pale Ale',
    SAISON = 'Saison',
    SOUR = 'Sour',
    LAMBIC = 'Lambic',
    BELGIAN_DUBBEL = 'Belgian Dubbel',
    BELGIAN_TRIPEL = 'Belgian Tripel' ,
    BELGIAN_GOLDEN_STRONG_ALE = 'Belgian Golden Strong Ale',
    BELGIAN_DARK_STRONG_ALE = 'Belgian Dark Strong Ale',
    ENGLISH_BARLEY_WINE = 'English Barley Wine',
    RAUCHBIER = 'Rauchbier',
    FRUITBIER = 'Fruit Beer'
    
}